### ISSUE TITLE
Feature Request Assign function to the power button

### ISSUE THREAD

**Issue by odmfl** [kia1349/DeskClock-final-java#1]
Hello could you implement the “dismiss / snooze / do nothing” function by pressing the power button?  Basically the same things you can currently do by pressing the volume keys.

**Comment by kia1349** [comment]
hi my dear friend
The alarm does not ring and does not fire at the scheduled time to check the rest and other .....

**Comment by odmfl** [comment]
hello, I found the app that allows you to do this, it also works well, I'll leave you the link if you want to contribute to the project

https://github.com/qw123wh/new-clock

**Comment by kia1349** [comment]
> hello, I found the app that allows you to do this, it also works well, I'll leave you the link if you want to contribute to the project
> 
> https://github.com/qw123wh/new-clock

thanks alot.
i try to test it.   :)
